export const taskKernelApplicationBoundary = {
  layer: "application",
  purpose: "Task Kernel command and query use cases live here after TK-05.",
} as const;

export type {
  ArchiveTaskCommandInput,
  BlockTaskCommandInput,
  CompleteTaskCommandInput,
  ConfirmHumanReviewCommandInput,
  ConfirmHumanReviewOutput,
  CreateTaskCommandInput,
  DeleteTaskCommandInput,
  GateReportItem,
  GetGateReportInput,
  GetGateReportOutput,
  GetMaterialsIssuesInput,
  GetMaterialsIssuesOutput,
  GetRelationGraphInput,
  GetRelationGraphOutput,
  GetReviewQueueInput,
  GetReviewQueueOutput,
  GetTaskDetailInput,
  GetTaskDetailOutput,
  ListTasksInput,
  ListTasksOutput,
  MaterialsIssue,
  RelationGraphEdge,
  RelationGraphNode,
  ReopenTaskCommandInput,
  ResolveTaskRefInput,
  ResolveTaskRefOutput,
  ReviewQueueItem,
  StartTaskCommandInput,
  SubmitAgentReviewCommandInput,
  TaskMutationOutput,
  TaskPackageDetail,
  TaskScopeInput,
  TaskSummary,
  UpdateTaskProgressCommandInput,
} from "./contracts.mjs";
export {
  taskCommandServicePlaceholder,
  TaskApplicationServicesPlaceholderLayer,
  TaskCommandServicePlaceholderLayer,
  taskQueryServicePlaceholder,
  TaskQueryServicePlaceholderLayer,
} from "./layers.mjs";
export {
  TASK_COMMAND_SERVICE_ID,
  TASK_QUERY_SERVICE_ID,
  TaskCommands,
  TaskCommandService,
  TaskQueries,
  TaskQueryService,
} from "./services.mjs";
export type {
  TaskCommandServiceShape,
  TaskQueryServiceShape,
} from "./services.mjs";
